# SC88XX Platform Support

ifeq ($(CONFIG_ARCH_SCX35),y)
sprd_isp-objs := isp_drv_kernel.o
obj-y += sprd_isp.o
endif

ifeq ($(CONFIG_ARCH_SC8825),y)
sprd_isp-objs := isp_drv_kernel.o
obj-y += sprd_isp.o
endif

