#
#***************************************************************
#
# Component = Linux Kernel Source Component.
#
# Copyright (C) 2002-2007 VirtualLogix SA.
#
# This program is free software;  you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# #ident  "@(#)Makefile.bin 1.10     07/10/23 VirtualLogix"
#
# Contributor(s):
#   Sebastien Laborie (sebastien.laborie@virtuallogix.com)
#
#***************************************************************
#

COMPONENT += LINUXKERNEL

LINUXKERNEL.all::

DEVTOOLS.crossdev:: $(LINUXKERNEL_DIR)/VMLINUX.conf
