
obj-$(CONFIG_FB_SC8825) := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o sprdfb_lcdc.o sprdfb_mcu.o sprdfb_rgb.o sprdfb_mipi.o sprdfb_i2c.o sprdfb_spi.o sprdfb_dsi.o sprdfb_chip_common.o sprdfb_chip_8825.o
obj-$(CONFIG_FB_SC8825) += dsi/
obj-$(CONFIG_FB_SC8825) += spi/

obj-$(CONFIG_FB_SCX35) := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o sprdfb_mcu.o sprdfb_rgb.o sprdfb_mipi.o sprdfb_i2c.o sprdfb_spi.o sprdfb_dsi.o  sprdfb_chip_common.o sprdfb_chip_8830.o
obj-$(CONFIG_FB_SCX35) += dsi/
obj-$(CONFIG_FB_SCX35) += spi/

obj-$(CONFIG_FB_LCD_HX8369) += lcd_hx8369.o
obj-$(CONFIG_FB_LCD_S6D0139) += lcd_s6d0139.o
obj-$(CONFIG_FB_LCD_NT35516_MCU) += lcd_nt35516_mcu.o
obj-$(CONFIG_FB_LCD_NT35516_MIPI) += lcd_nt35516_mipi.o
obj-$(CONFIG_FB_LCD_NT35516_RGB_I2C) += lcd_nt35516_rgb_i2c.o
obj-$(CONFIG_FB_LCD_NT35516_RGB_SPI) += lcd_nt35516_rgb_spi.o
obj-$(CONFIG_FB_LCD_NT35510_MIPI) += lcd_nt35510_mipi.o
obj-$(CONFIG_FB_LCD_NT35512_MIPI) += lcd_nt35512_mipi.o
obj-$(CONFIG_FB_LCD_OTM8018B_MIPI) += lcd_otm_8018b_mipi.o
obj-$(CONFIG_FB_LCD_SSD2075_MIPI) += lcd_ssd2075_mipi.o
obj-$(CONFIG_FB_LCD_NT51017_MIPI_LVDS) += lcd_nt51017_mipi_lvds.o
