# SC88XX Platform Support
ifeq ($(CONFIG_ARCH_SC8810),y)
sprd_rotation-objs := rotation_drv.o
obj-y += sprd_rotation.o
endif

ifeq ($(CONFIG_ARCH_SC8825),y)
sprd_rotation-objs := rot_drv.o
obj-y += sprd_rotation.o
endif

