#
#***************************************************************
#
# Component = Nano-Kernel device driver interface (NK DDI)
#
# Copyright (C) 2002-2005 Jaluna SA.
#
# This program is free software;  you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# #ident  "@(#)Makefile 1.1     07/10/18 VirtualLogix"
#
# Contributor(s):
#   Eric Lescouet <eric@lescouet.org> - Jaluna SA
#
#***************************************************************
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NKERNEL)         += nkspc.o
