obj-y += io.o irq.o timer.o devices.o arch_asm.o arch_init.o globalregs.o \
         clock_common.o clock_sc8810.o regulator.o regulator-devices.o \
         dma.o reserve.o

obj-y += adi.o pin.o gpio.o eic.o adc.o efuse.o

obj-$(CONFIG_MACH_SP8810GA) += board-sp8810ga.o
obj-$(CONFIG_MACH_SP6820GA) += board-sp6820ga.o
