# SC88XX Platform Support

obj-$(CONFIG_SND_SC88XX_SOC_SPRDPHONE) += sprdphone.o vbc-codec.o sc88xx-vbc.o sc88xx-pcm.o aud_enha_exp.o aud_enha_config.o audio_dev_hal.o filter_calc.o vb_phy_v3.o dol_phy_v0.o
