#!/bin/bash

DEBUGFS_TOP_DIR="/sys/kernel/debug/"
BM_DIR_PRE="bus_monitor"
BM_DIR_PATH=""
RW_MODE="0x00000000"

BM_CMD_CLR_INT="0x28000001"
BM_CMD_ENABLE="0x10000001"
BM_CMD_DISABLE="0x00000000"
#performance without interrupt
BM_CMD_COUNT_START="0x0000000b"
BM_CMD_COUNT_STOP="0x00000003"
BM_CMD_RESETBUF_START="0x01000001"
BM_CMD_RESETBUF_STOP="0x00000001"
BM_CMD_RESETBUF_R_READ="0x2000001"
BM_CMD_RESETBUF_W_READ="0x4000001"
BM_CMD_GLB_ENABLE="bm_glb_enable"
BM_CMD_GLB_DISABLEi="bm_glb_disable"
BM_CMD_GLB_COUNT_START="bm_glb_count_start"
BM_CMD_GLB_COUNT_STOP="bm_glb_count_stop"

if [ ${1} = "-h" ];then
#show some help information
	echo Usage:	
	echo ./busmonitor.sh arg1 arg2
	echo arg1:	busmonitor id
	echo	the busmonitor id list following:
	echo busmonitor	id
	echo	axi bm3    3
	echo arg2: start or stop reset buffer / reset buffer info

	exit 0
fi

BM_DIR_PATH=${DEBUGFS_TOP_DIR}${BM_DIR_PRE}$1"/"

if [ ${2} = "start" ];then
	#enable bm(global)
	echo ${BM_CMD_GLB_ENABLE} > ${BM_DIR_PRE}"glb_ctl"
	#clean the busmonitor interrupt status and reset buffer
	echo ${BM_CMD_CLR_INT} > ${BM_DIR_PATH}"intc"
	#disable busmonitor
	echo ${BM_CMD_DISABLE} > ${BM_DIR_PATH}"intc"
	#start bm count
	echo ${BM_CMD_RESETBUF_START} > ${BM_DIR_PATH}"intc"
fi

if [ ${2} = "stop" ];then
	#stop reset buf
	echo ${BM_CMD_RESETBUF_STOP} > ${BM_DIR_PATH}"intc"
fi

if [ ${2} =  "info" ];then
	echo ${BM_CMD_RESETBUF_R_READ} > ${BM_DIR_PATH}"intc"
	echo "last 4 read command addr:"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"

	echo ${BM_CMD_RESETBUF_W_READ} > ${BM_DIR_PATH}"intc"
	echo "last 4 write command addr:"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"
	cat ${BM_DIR_PATH}"match_addr"
fi

exit 1
