ifeq ($(CONFIG_ARCH_SCX35), y)
obj-$(CONFIG_SPRD_BUSMONITOR) += sc8830_bm.o
obj-$(CONFIG_SPRD_BUSMONITOR) += bm_test.o
else
obj-$(CONFIG_SPRD_BUSMONITOR_CORE) += sprd_busmonitor_core.o
obj-$(CONFIG_SPRD_BUSMONITOR) += sprd_busmonitor.o
endif
