# SC88XX Platform Support
obj-$(CONFIG_SND_SC88XX_SOC_SPRDPHONE) += sprdphone.o
obj-$(CONFIG_SND_SC88XX_SOC)           += sc88xx-pcm.o
obj-$(CONFIG_SND_SC88XX_SOC_VBC)       += sc88xx-vbc.o
obj-$(CONFIG_SND_SOC_VBC)              += vbc-codec.o vbc-codec-eq.o speaker-pa.o audio_dev_hal.o filter_calc.o vb_phy_v3.o dol_phy_v0.o
