# SPRD Platform Support
snd-soc-sc881x-objs         		:= sc881x.o
obj-$(CONFIG_SND_SPRD_SOC_SC881X)    	+= snd-soc-sc881x.o
snd-soc-sc882x-objs         		:= sc882x.o
obj-$(CONFIG_SND_SPRD_SOC_SC882X)    	+= snd-soc-sc882x.o
snd-soc-sc8830-objs         		:= sc8830.o
obj-$(CONFIG_SND_SPRD_SOC_SC8830)    	+= snd-soc-sc8830.o

obj-$(CONFIG_SND_SPEAKER_PA)         	+= speaker-pa.o

obj-$(CONFIG_SND_SPRD_SOC_VBC)	     	+= dai/vbc/
obj-$(CONFIG_SND_SPRD_SOC_VBC_R2P0)	+= dai/vbc/
obj-$(CONFIG_SND_SPRD_SOC_VAUDIO)     	+= dai/vaudio/
obj-$(CONFIG_SND_SPRD_SOC_I2S)		+= dai/i2s/
obj-$(CONFIG_SND_SOC_DOLPHIN)		+= codec/dolphin/
obj-$(CONFIG_SND_SOC_SPRD_CODEC)	+= codec/sprd/
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V3)	+= codec/sprd/
