# SPRD Platform Support
snd-soc-shark-objs         		:= vbc-r2p0-sprd-codec-v3.o
obj-$(CONFIG_SND_SOC_SPRD_VBC_R2P0_SPRD_CODEC_V3)    	+= snd-soc-shark.o
snd-soc-i2s-objs         		:= i2s-r0p0-null-codec.o
obj-$(CONFIG_SND_SOC_SPRD_I2S_V0_NULL_CODEC)    	+= snd-soc-i2s.o
obj-$(CONFIG_SND_SOC_SPRD) += sprd-asoc-common.o

obj-$(CONFIG_SND_SOC_SPRD_AUDIO_DMA)	+= dai/
obj-$(CONFIG_SND_SOC_SPRD_VBC_R2P0)	+= dai/vbc/
obj-$(CONFIG_SND_SOC_SPRD_VAUDIO)     	+= dai/vaudio/
obj-$(CONFIG_SND_SOC_SPRD_I2S)		+= dai/i2s/
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V3)	+= codec/sprd/
obj-$(CONFIG_SND_SOC_NULL_CODEC)	+= codec/null-codec/
