/*
 *  linux/include/asm-arm/arch-osware/debug-macros.S
 *
 *  Copyright (C) 2006 Jaluna SA.
 *
 * This program is free software;  you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

		.macro	addruart,rx
		.endm

		.macro	senduart,rd,rx
		.endm

		.macro	busyuart,rd,rx
		.endm

		.macro	waituart,rd,rx
		.endm
