snd-soc-sprd-sprd-codec-objs   := sprd-codec.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC)        += snd-soc-sprd-sprd-codec.o
snd-soc-sprd-sprd-codec-v2-objs   := sprd-codec-v2.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V2)        += snd-soc-sprd-sprd-codec-v2.o
