snd-soc-sprd-sprd-codec-objs   := sprd-codec.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC)        += snd-soc-sprd-sprd-codec.o
snd-soc-sprd-sprd-codec-v3-objs   := sprd-codec-v3.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V3)        += snd-soc-sprd-sprd-codec-v3.o
