# SPRD VBC Support
SPRD_SOUND_TREE := sound/soc/sprd/
KBUILD_CFLAGS	+= -I$(SPRD_SOUND_TREE) -I$(SPRD_SOUND_TREE)/dai

snd-soc-sprd-vbc-r2p0-objs       := vbc.o
obj-$(CONFIG_SND_SOC_SPRD_VBC_R2P0)    += snd-soc-sprd-vbc-r2p0.o
