/*
 * Copyright (C) 2012 Spreadtrum Communications Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 ************************************************
 * Automatically generated C config: don't edit *
 ************************************************
 */

#ifndef __CTL_PIN_H__
#define __CTL_PIN_H__

#define CTL_PIN

/* registers definitions for controller CTL_PIN */
#define REG_PIN_ANA_INT                 SCI_ADDRESS(CTL_PIN_BASE, 0x0004)
#define REG_PIN_EXT_RST_B               SCI_ADDRESS(CTL_PIN_BASE, 0x0008)
#define REG_PIN_CHIP_SLEEP              SCI_ADDRESS(CTL_PIN_BASE, 0x000c)
#define REG_PIN_XTL_BUF_EN              SCI_ADDRESS(CTL_PIN_BASE, 0x0010)
#define REG_PIN_VBDA_D                  SCI_ADDRESS(CTL_PIN_BASE, 0x0014)
#define REG_PIN_VBDA_LR                 SCI_ADDRESS(CTL_PIN_BASE, 0x0018)
#define REG_PIN_VBDA_SCLK               SCI_ADDRESS(CTL_PIN_BASE, 0x001c)
#define REG_PIN_VBAD_D                  SCI_ADDRESS(CTL_PIN_BASE, 0x0020)
#define REG_PIN_VBAD_LR                 SCI_ADDRESS(CTL_PIN_BASE, 0x0024)
#define REG_PIN_VBAD_SCLK               SCI_ADDRESS(CTL_PIN_BASE, 0x0028)
#define REG_PIN_TD_TXPD                 SCI_ADDRESS(CTL_PIN_BASE, 0x002c)
#define REG_PIN_TD_RXPD                 SCI_ADDRESS(CTL_PIN_BASE, 0x0030)
#define REG_PIN_GSM_TXPD                SCI_ADDRESS(CTL_PIN_BASE, 0x0034)
#define REG_PIN_GSM_RXPD                SCI_ADDRESS(CTL_PIN_BASE, 0x0038)
#define REG_PIN_TD_RX_CLK               SCI_ADDRESS(CTL_PIN_BASE, 0x003c)
#define REG_PIN_CLK_32K                 SCI_ADDRESS(CTL_PIN_BASE, 0x0040)
#define REG_PIN_CLK_26M                 SCI_ADDRESS(CTL_PIN_BASE, 0x0044)
#define REG_PIN_ADI_D                   SCI_ADDRESS(CTL_PIN_BASE, 0x0048)
#define REG_PIN_ADI_SYNC                SCI_ADDRESS(CTL_PIN_BASE, 0x004c)
#define REG_PIN_ADI_SCLK                SCI_ADDRESS(CTL_PIN_BASE, 0x0050)
#define REG_PIN_IF_SPR                  SCI_ADDRESS(CTL_PIN_BASE, 0x0054)
#define REG_PIN_COM_TX_APCD             SCI_ADDRESS(CTL_PIN_BASE, 0x0058)
#define REG_PIN_COM_TX_DQ1              SCI_ADDRESS(CTL_PIN_BASE, 0x005c)
#define REG_PIN_COM_TX_DQ0              SCI_ADDRESS(CTL_PIN_BASE, 0x0060)
#define REG_PIN_COM_TX_DI1              SCI_ADDRESS(CTL_PIN_BASE, 0x0064)
#define REG_PIN_COM_TX_DI0              SCI_ADDRESS(CTL_PIN_BASE, 0x0068)
#define REG_PIN_COM_TX_SYNC             SCI_ADDRESS(CTL_PIN_BASE, 0x006c)
#define REG_PIN_COM_TX_SCLK             SCI_ADDRESS(CTL_PIN_BASE, 0x0070)
#define REG_PIN_COM_RX_DQ1              SCI_ADDRESS(CTL_PIN_BASE, 0x0074)
#define REG_PIN_COM_RX_DQ0              SCI_ADDRESS(CTL_PIN_BASE, 0x0078)
#define REG_PIN_COM_RX_DI1              SCI_ADDRESS(CTL_PIN_BASE, 0x007c)
#define REG_PIN_COM_RX_DI0              SCI_ADDRESS(CTL_PIN_BASE, 0x0080)
#define REG_PIN_COM_RX_SYNC             SCI_ADDRESS(CTL_PIN_BASE, 0x0084)
#define REG_PIN_COM_RX_SCLK             SCI_ADDRESS(CTL_PIN_BASE, 0x0088)
#define REG_PIN_SIMCLK0                 SCI_ADDRESS(CTL_PIN_BASE, 0x008c)
#define REG_PIN_SIMDA0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0090)
#define REG_PIN_SIMRST0                 SCI_ADDRESS(CTL_PIN_BASE, 0x0094)
#define REG_PIN_SIMCLK1                 SCI_ADDRESS(CTL_PIN_BASE, 0x0098)
#define REG_PIN_SIMDA1                  SCI_ADDRESS(CTL_PIN_BASE, 0x009c)
#define REG_PIN_SIMRST1                 SCI_ADDRESS(CTL_PIN_BASE, 0x00a0)
#define REG_PIN_SD0_CLK                 SCI_ADDRESS(CTL_PIN_BASE, 0x00a4)
#define REG_PIN_SD_CMD                  SCI_ADDRESS(CTL_PIN_BASE, 0x00a8)
#define REG_PIN_SD_D0                   SCI_ADDRESS(CTL_PIN_BASE, 0x00ac)
#define REG_PIN_SD_D1                   SCI_ADDRESS(CTL_PIN_BASE, 0x00b0)
#define REG_PIN_SD_D2                   SCI_ADDRESS(CTL_PIN_BASE, 0x00b4)
#define REG_PIN_SD_D3                   SCI_ADDRESS(CTL_PIN_BASE, 0x00b8)
#define REG_PIN_SD1_CLK                 SCI_ADDRESS(CTL_PIN_BASE, 0x00bc)
#define REG_PIN_KEYOUT0                 SCI_ADDRESS(CTL_PIN_BASE, 0x00c0)
#define REG_PIN_KEYOUT1                 SCI_ADDRESS(CTL_PIN_BASE, 0x00c4)
#define REG_PIN_KEYOUT2                 SCI_ADDRESS(CTL_PIN_BASE, 0x00c8)
#define REG_PIN_KEYOUT3                 SCI_ADDRESS(CTL_PIN_BASE, 0x00cc)
#define REG_PIN_KEYOUT4                 SCI_ADDRESS(CTL_PIN_BASE, 0x00d0)
#define REG_PIN_KEYOUT5                 SCI_ADDRESS(CTL_PIN_BASE, 0x00d4)
#define REG_PIN_KEYOUT6                 SCI_ADDRESS(CTL_PIN_BASE, 0x00d8)
#define REG_PIN_KEYOUT7                 SCI_ADDRESS(CTL_PIN_BASE, 0x00dc)
#define REG_PIN_KEYIN0                  SCI_ADDRESS(CTL_PIN_BASE, 0x00e0)
#define REG_PIN_KEYIN1                  SCI_ADDRESS(CTL_PIN_BASE, 0x00e4)
#define REG_PIN_KEYIN2                  SCI_ADDRESS(CTL_PIN_BASE, 0x00e8)
#define REG_PIN_KEYIN3                  SCI_ADDRESS(CTL_PIN_BASE, 0x00ec)
#define REG_PIN_KEYIN4                  SCI_ADDRESS(CTL_PIN_BASE, 0x00f0)
#define REG_PIN_KEYIN5                  SCI_ADDRESS(CTL_PIN_BASE, 0x00f4)
#define REG_PIN_KEYIN6                  SCI_ADDRESS(CTL_PIN_BASE, 0x00f8)
#define REG_PIN_KEYIN7                  SCI_ADDRESS(CTL_PIN_BASE, 0x00fc)
#define REG_PIN_SPI_DI                  SCI_ADDRESS(CTL_PIN_BASE, 0x0100)
#define REG_PIN_SPI_CLK                 SCI_ADDRESS(CTL_PIN_BASE, 0x0104)
#define REG_PIN_SPI_DO                  SCI_ADDRESS(CTL_PIN_BASE, 0x0108)
#define REG_PIN_SPI_CSN0                SCI_ADDRESS(CTL_PIN_BASE, 0x010c)
#define REG_PIN_SPI_CSN1                SCI_ADDRESS(CTL_PIN_BASE, 0x0110)
#define REG_PIN_MTDO                    SCI_ADDRESS(CTL_PIN_BASE, 0x0114)
#define REG_PIN_MTDI                    SCI_ADDRESS(CTL_PIN_BASE, 0x0118)
#define REG_PIN_MTCK                    SCI_ADDRESS(CTL_PIN_BASE, 0x011c)
#define REG_PIN_MTMS                    SCI_ADDRESS(CTL_PIN_BASE, 0x0120)
#define REG_PIN_MTRST_N                 SCI_ADDRESS(CTL_PIN_BASE, 0x0124)
#define REG_PIN_U0TXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x0128)
#define REG_PIN_U0RXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x012c)
#define REG_PIN_U0CTS                   SCI_ADDRESS(CTL_PIN_BASE, 0x0130)
#define REG_PIN_U0RTS                   SCI_ADDRESS(CTL_PIN_BASE, 0x0134)
#define REG_PIN_U1TXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x0138)
#define REG_PIN_U1RXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x013c)
#define REG_PIN_NFWPN                   SCI_ADDRESS(CTL_PIN_BASE, 0x0140)
#define REG_PIN_NFRB                    SCI_ADDRESS(CTL_PIN_BASE, 0x0144)
#define REG_PIN_NFCLE                   SCI_ADDRESS(CTL_PIN_BASE, 0x0148)
#define REG_PIN_NFALE                   SCI_ADDRESS(CTL_PIN_BASE, 0x014c)
#define REG_PIN_NFCEN0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0150)
#define REG_PIN_NFWEN                   SCI_ADDRESS(CTL_PIN_BASE, 0x0154)
#define REG_PIN_NFREN                   SCI_ADDRESS(CTL_PIN_BASE, 0x0158)
#define REG_PIN_NFD0                    SCI_ADDRESS(CTL_PIN_BASE, 0x015c)
#define REG_PIN_NFD1                    SCI_ADDRESS(CTL_PIN_BASE, 0x0160)
#define REG_PIN_NFD2                    SCI_ADDRESS(CTL_PIN_BASE, 0x0164)
#define REG_PIN_NFD3                    SCI_ADDRESS(CTL_PIN_BASE, 0x0168)
#define REG_PIN_NFD4                    SCI_ADDRESS(CTL_PIN_BASE, 0x016c)
#define REG_PIN_NFD5                    SCI_ADDRESS(CTL_PIN_BASE, 0x0170)
#define REG_PIN_NFD6                    SCI_ADDRESS(CTL_PIN_BASE, 0x0174)
#define REG_PIN_NFD7                    SCI_ADDRESS(CTL_PIN_BASE, 0x0178)
#define REG_PIN_NFD8                    SCI_ADDRESS(CTL_PIN_BASE, 0x017c)
#define REG_PIN_NFD9                    SCI_ADDRESS(CTL_PIN_BASE, 0x0180)
#define REG_PIN_NFD10                   SCI_ADDRESS(CTL_PIN_BASE, 0x0184)
#define REG_PIN_NFD11                   SCI_ADDRESS(CTL_PIN_BASE, 0x0188)
#define REG_PIN_NFD12                   SCI_ADDRESS(CTL_PIN_BASE, 0x018c)
#define REG_PIN_NFD13                   SCI_ADDRESS(CTL_PIN_BASE, 0x0190)
#define REG_PIN_NFD14                   SCI_ADDRESS(CTL_PIN_BASE, 0x0194)
#define REG_PIN_NFD15                   SCI_ADDRESS(CTL_PIN_BASE, 0x0198)
#define REG_PIN_EMRST_N                 SCI_ADDRESS(CTL_PIN_BASE, 0x019c)
#define REG_PIN_EMA0                    SCI_ADDRESS(CTL_PIN_BASE, 0x01a0)
#define REG_PIN_EMA1                    SCI_ADDRESS(CTL_PIN_BASE, 0x01a4)
#define REG_PIN_EMA2                    SCI_ADDRESS(CTL_PIN_BASE, 0x01a8)
#define REG_PIN_EMA3                    SCI_ADDRESS(CTL_PIN_BASE, 0x01ac)
#define REG_PIN_EMA4                    SCI_ADDRESS(CTL_PIN_BASE, 0x01b0)
#define REG_PIN_EMA5                    SCI_ADDRESS(CTL_PIN_BASE, 0x01b4)
#define REG_PIN_EMA6                    SCI_ADDRESS(CTL_PIN_BASE, 0x01b8)
#define REG_PIN_EMA7                    SCI_ADDRESS(CTL_PIN_BASE, 0x01bc)
#define REG_PIN_EMA8                    SCI_ADDRESS(CTL_PIN_BASE, 0x01c0)
#define REG_PIN_EMA9                    SCI_ADDRESS(CTL_PIN_BASE, 0x01c4)
#define REG_PIN_EMA10                   SCI_ADDRESS(CTL_PIN_BASE, 0x01c8)
#define REG_PIN_EMA11                   SCI_ADDRESS(CTL_PIN_BASE, 0x01cc)
#define REG_PIN_EMA12                   SCI_ADDRESS(CTL_PIN_BASE, 0x01d0)
#define REG_PIN_EMA13                   SCI_ADDRESS(CTL_PIN_BASE, 0x01d4)
#define REG_PIN_EMCKE1                  SCI_ADDRESS(CTL_PIN_BASE, 0x01d8)
#define REG_PIN_EMD0                    SCI_ADDRESS(CTL_PIN_BASE, 0x01dc)
#define REG_PIN_EMD1                    SCI_ADDRESS(CTL_PIN_BASE, 0x01e0)
#define REG_PIN_EMD2                    SCI_ADDRESS(CTL_PIN_BASE, 0x01e4)
#define REG_PIN_EMD3                    SCI_ADDRESS(CTL_PIN_BASE, 0x01e8)
#define REG_PIN_EMD4                    SCI_ADDRESS(CTL_PIN_BASE, 0x01ec)
#define REG_PIN_EMD5                    SCI_ADDRESS(CTL_PIN_BASE, 0x01f0)
#define REG_PIN_EMD6                    SCI_ADDRESS(CTL_PIN_BASE, 0x01f4)
#define REG_PIN_EMD7                    SCI_ADDRESS(CTL_PIN_BASE, 0x01f8)
#define REG_PIN_EMDQM0                  SCI_ADDRESS(CTL_PIN_BASE, 0x01fc)
#define REG_PIN_EMDQS0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0200)
#define REG_PIN_EMD8                    SCI_ADDRESS(CTL_PIN_BASE, 0x0204)
#define REG_PIN_EMD9                    SCI_ADDRESS(CTL_PIN_BASE, 0x0208)
#define REG_PIN_EMD10                   SCI_ADDRESS(CTL_PIN_BASE, 0x020c)
#define REG_PIN_EMD11                   SCI_ADDRESS(CTL_PIN_BASE, 0x0210)
#define REG_PIN_EMD12                   SCI_ADDRESS(CTL_PIN_BASE, 0x0214)
#define REG_PIN_EMD13                   SCI_ADDRESS(CTL_PIN_BASE, 0x0218)
#define REG_PIN_EMD14                   SCI_ADDRESS(CTL_PIN_BASE, 0x021c)
#define REG_PIN_EMD15                   SCI_ADDRESS(CTL_PIN_BASE, 0x0220)
#define REG_PIN_EMDQM1                  SCI_ADDRESS(CTL_PIN_BASE, 0x0224)
#define REG_PIN_EMDQS1                  SCI_ADDRESS(CTL_PIN_BASE, 0x0228)
#define REG_PIN_EMD16                   SCI_ADDRESS(CTL_PIN_BASE, 0x022c)
#define REG_PIN_EMD17                   SCI_ADDRESS(CTL_PIN_BASE, 0x0230)
#define REG_PIN_EMD18                   SCI_ADDRESS(CTL_PIN_BASE, 0x0234)
#define REG_PIN_EMD19                   SCI_ADDRESS(CTL_PIN_BASE, 0x0238)
#define REG_PIN_EMD20                   SCI_ADDRESS(CTL_PIN_BASE, 0x023c)
#define REG_PIN_EMD21                   SCI_ADDRESS(CTL_PIN_BASE, 0x0240)
#define REG_PIN_EMD22                   SCI_ADDRESS(CTL_PIN_BASE, 0x0244)
#define REG_PIN_EMD23                   SCI_ADDRESS(CTL_PIN_BASE, 0x0248)
#define REG_PIN_EMDQM2                  SCI_ADDRESS(CTL_PIN_BASE, 0x024c)
#define REG_PIN_EMDQS2                  SCI_ADDRESS(CTL_PIN_BASE, 0x0250)
#define REG_PIN_EMD24                   SCI_ADDRESS(CTL_PIN_BASE, 0x0254)
#define REG_PIN_EMD25                   SCI_ADDRESS(CTL_PIN_BASE, 0x0258)
#define REG_PIN_EMD26                   SCI_ADDRESS(CTL_PIN_BASE, 0x025c)
#define REG_PIN_EMD27                   SCI_ADDRESS(CTL_PIN_BASE, 0x0260)
#define REG_PIN_EMD28                   SCI_ADDRESS(CTL_PIN_BASE, 0x0264)
#define REG_PIN_EMD29                   SCI_ADDRESS(CTL_PIN_BASE, 0x0268)
#define REG_PIN_EMD30                   SCI_ADDRESS(CTL_PIN_BASE, 0x026c)
#define REG_PIN_EMD31                   SCI_ADDRESS(CTL_PIN_BASE, 0x0270)
#define REG_PIN_EMDQM3                  SCI_ADDRESS(CTL_PIN_BASE, 0x0274)
#define REG_PIN_EMDQS3                  SCI_ADDRESS(CTL_PIN_BASE, 0x0278)
#define REG_PIN_CLKDPMEM                SCI_ADDRESS(CTL_PIN_BASE, 0x027c)
#define REG_PIN_CLKDMMEM                SCI_ADDRESS(CTL_PIN_BASE, 0x0280)
#define REG_PIN_EMRAS_N                 SCI_ADDRESS(CTL_PIN_BASE, 0x0284)
#define REG_PIN_EMCAS_N                 SCI_ADDRESS(CTL_PIN_BASE, 0x0288)
#define REG_PIN_EMWE_N                  SCI_ADDRESS(CTL_PIN_BASE, 0x028c)
#define REG_PIN_EMCS_N0                 SCI_ADDRESS(CTL_PIN_BASE, 0x0290)
#define REG_PIN_EMCS_N1                 SCI_ADDRESS(CTL_PIN_BASE, 0x0294)
#define REG_PIN_EMGPRE_LOOP             SCI_ADDRESS(CTL_PIN_BASE, 0x0298)
#define REG_PIN_EMGPST_LOOP             SCI_ADDRESS(CTL_PIN_BASE, 0x029c)
#define REG_PIN_EMBA0                   SCI_ADDRESS(CTL_PIN_BASE, 0x02a0)
#define REG_PIN_EMBA1                   SCI_ADDRESS(CTL_PIN_BASE, 0x02a4)
#define REG_PIN_EMCKE0                  SCI_ADDRESS(CTL_PIN_BASE, 0x02a8)
#define REG_PIN_LCD_CSN1                SCI_ADDRESS(CTL_PIN_BASE, 0x02ac)
#define REG_PIN_LCD_RSTN                SCI_ADDRESS(CTL_PIN_BASE, 0x02b0)
#define REG_PIN_LCD_CD                  SCI_ADDRESS(CTL_PIN_BASE, 0x02b4)
#define REG_PIN_LCD_D0                  SCI_ADDRESS(CTL_PIN_BASE, 0x02b8)
#define REG_PIN_LCD_D1                  SCI_ADDRESS(CTL_PIN_BASE, 0x02bc)
#define REG_PIN_LCD_D2                  SCI_ADDRESS(CTL_PIN_BASE, 0x02c0)
#define REG_PIN_LCD_D3                  SCI_ADDRESS(CTL_PIN_BASE, 0x02c4)
#define REG_PIN_LCD_D4                  SCI_ADDRESS(CTL_PIN_BASE, 0x02c8)
#define REG_PIN_LCD_D5                  SCI_ADDRESS(CTL_PIN_BASE, 0x02cc)
#define REG_PIN_LCD_D6                  SCI_ADDRESS(CTL_PIN_BASE, 0x02d0)
#define REG_PIN_LCD_D7                  SCI_ADDRESS(CTL_PIN_BASE, 0x02d4)
#define REG_PIN_LCD_D8                  SCI_ADDRESS(CTL_PIN_BASE, 0x02d8)
#define REG_PIN_LCD_WRN                 SCI_ADDRESS(CTL_PIN_BASE, 0x02dc)
#define REG_PIN_LCD_RDN                 SCI_ADDRESS(CTL_PIN_BASE, 0x02e0)
#define REG_PIN_LCD_CSN0                SCI_ADDRESS(CTL_PIN_BASE, 0x02e4)
#define REG_PIN_LCD_D9                  SCI_ADDRESS(CTL_PIN_BASE, 0x02e8)
#define REG_PIN_LCD_D10                 SCI_ADDRESS(CTL_PIN_BASE, 0x02ec)
#define REG_PIN_LCD_D11                 SCI_ADDRESS(CTL_PIN_BASE, 0x02f0)
#define REG_PIN_LCD_D12                 SCI_ADDRESS(CTL_PIN_BASE, 0x02f4)
#define REG_PIN_LCD_D13                 SCI_ADDRESS(CTL_PIN_BASE, 0x02f8)
#define REG_PIN_LCD_D14                 SCI_ADDRESS(CTL_PIN_BASE, 0x02fc)
#define REG_PIN_LCD_D15                 SCI_ADDRESS(CTL_PIN_BASE, 0x0300)
#define REG_PIN_LCD_D16                 SCI_ADDRESS(CTL_PIN_BASE, 0x0304)
#define REG_PIN_LCD_D17                 SCI_ADDRESS(CTL_PIN_BASE, 0x0308)
#define REG_PIN_LCD_FMARK               SCI_ADDRESS(CTL_PIN_BASE, 0x030c)
#define REG_PIN_CCIRMCLK                SCI_ADDRESS(CTL_PIN_BASE, 0x0310)
#define REG_PIN_CCIRCK                  SCI_ADDRESS(CTL_PIN_BASE, 0x0314)
#define REG_PIN_CCIRHS                  SCI_ADDRESS(CTL_PIN_BASE, 0x0318)
#define REG_PIN_CCIRVS                  SCI_ADDRESS(CTL_PIN_BASE, 0x031c)
#define REG_PIN_CCIRD0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0320)
#define REG_PIN_CCIRD1                  SCI_ADDRESS(CTL_PIN_BASE, 0x0324)
#define REG_PIN_CCIRD2                  SCI_ADDRESS(CTL_PIN_BASE, 0x0328)
#define REG_PIN_CCIRD3                  SCI_ADDRESS(CTL_PIN_BASE, 0x032c)
#define REG_PIN_CCIRD4                  SCI_ADDRESS(CTL_PIN_BASE, 0x0330)
#define REG_PIN_CCIRD5                  SCI_ADDRESS(CTL_PIN_BASE, 0x0334)
#define REG_PIN_CCIRD6                  SCI_ADDRESS(CTL_PIN_BASE, 0x0338)
#define REG_PIN_CCIRD7                  SCI_ADDRESS(CTL_PIN_BASE, 0x033c)
#define REG_PIN_CCIRRST                 SCI_ADDRESS(CTL_PIN_BASE, 0x0340)
#define REG_PIN_CCIRPD1                 SCI_ADDRESS(CTL_PIN_BASE, 0x0344)
#define REG_PIN_CCIRPD0                 SCI_ADDRESS(CTL_PIN_BASE, 0x0348)
#define REG_PIN_SCL                     SCI_ADDRESS(CTL_PIN_BASE, 0x034c)
#define REG_PIN_SDA                     SCI_ADDRESS(CTL_PIN_BASE, 0x0350)
#define REG_PIN_CLK_AUX0                SCI_ADDRESS(CTL_PIN_BASE, 0x0354)
#define REG_PIN_IISDI                   SCI_ADDRESS(CTL_PIN_BASE, 0x0358)
#define REG_PIN_IISDO                   SCI_ADDRESS(CTL_PIN_BASE, 0x035c)
#define REG_PIN_IISCLK                  SCI_ADDRESS(CTL_PIN_BASE, 0x0360)
#define REG_PIN_IISLRCK                 SCI_ADDRESS(CTL_PIN_BASE, 0x0364)
#define REG_PIN_IISMCK                  SCI_ADDRESS(CTL_PIN_BASE, 0x0368)
#define REG_PIN_RFSDA0                  SCI_ADDRESS(CTL_PIN_BASE, 0x036c)
#define REG_PIN_RFSCK0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0370)
#define REG_PIN_RFSEN0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0374)
#define REG_PIN_RFCTL0                  SCI_ADDRESS(CTL_PIN_BASE, 0x0378)
#define REG_PIN_RFCTL1                  SCI_ADDRESS(CTL_PIN_BASE, 0x037c)
#define REG_PIN_RFCTL2                  SCI_ADDRESS(CTL_PIN_BASE, 0x0380)
#define REG_PIN_RFCTL3                  SCI_ADDRESS(CTL_PIN_BASE, 0x0384)
#define REG_PIN_RFCTL4                  SCI_ADDRESS(CTL_PIN_BASE, 0x0388)
#define REG_PIN_RFCTL5                  SCI_ADDRESS(CTL_PIN_BASE, 0x038c)
#define REG_PIN_RFCTL6                  SCI_ADDRESS(CTL_PIN_BASE, 0x0390)
#define REG_PIN_RFCTL7                  SCI_ADDRESS(CTL_PIN_BASE, 0x0394)
#define REG_PIN_RFCTL8                  SCI_ADDRESS(CTL_PIN_BASE, 0x0398)
#define REG_PIN_RFCTL9                  SCI_ADDRESS(CTL_PIN_BASE, 0x039c)
#define REG_PIN_RFCTL10                 SCI_ADDRESS(CTL_PIN_BASE, 0x03a0)
#define REG_PIN_RFCTL11                 SCI_ADDRESS(CTL_PIN_BASE, 0x03a4)
#define REG_PIN_RFCTL12                 SCI_ADDRESS(CTL_PIN_BASE, 0x03a8)
#define REG_PIN_RFCTL13                 SCI_ADDRESS(CTL_PIN_BASE, 0x03ac)
#define REG_PIN_RFCTL14                 SCI_ADDRESS(CTL_PIN_BASE, 0x03b0)
#define REG_PIN_RFCTL15                 SCI_ADDRESS(CTL_PIN_BASE, 0x03b4)
#define REG_PIN_XTL_EN                  SCI_ADDRESS(CTL_PIN_BASE, 0x03b8)
#define REG_PIN_PTEST                   SCI_ADDRESS(CTL_PIN_BASE, 0x03bc)
#define REG_PIN_GPIO135                 SCI_ADDRESS(CTL_PIN_BASE, 0x03c0)
#define REG_PIN_GPIO136                 SCI_ADDRESS(CTL_PIN_BASE, 0x03c4)
#define REG_PIN_GPIO137                 SCI_ADDRESS(CTL_PIN_BASE, 0x03c8)
#define REG_PIN_GPIO138                 SCI_ADDRESS(CTL_PIN_BASE, 0x03cc)
#define REG_PIN_GPIO139                 SCI_ADDRESS(CTL_PIN_BASE, 0x03d0)
#define REG_PIN_GPIO140                 SCI_ADDRESS(CTL_PIN_BASE, 0x03d4)
#define REG_PIN_GPIO141                 SCI_ADDRESS(CTL_PIN_BASE, 0x03d8)
#define REG_PIN_GPIO142                 SCI_ADDRESS(CTL_PIN_BASE, 0x03dc)
#define REG_PIN_GPIO143                 SCI_ADDRESS(CTL_PIN_BASE, 0x03e0)
#define REG_PIN_GPIO144                 SCI_ADDRESS(CTL_PIN_BASE, 0x03e4)
#define REG_PIN_SD2_CLK                 SCI_ADDRESS(CTL_PIN_BASE, 0x03e8)
#define REG_PIN_SD2_CMD                 SCI_ADDRESS(CTL_PIN_BASE, 0x03ec)
#define REG_PIN_SD2_D0                  SCI_ADDRESS(CTL_PIN_BASE, 0x03f0)
#define REG_PIN_SD2_D1                  SCI_ADDRESS(CTL_PIN_BASE, 0x03f4)
#define REG_PIN_SD2_D2                  SCI_ADDRESS(CTL_PIN_BASE, 0x03f8)
#define REG_PIN_SD2_D3                  SCI_ADDRESS(CTL_PIN_BASE, 0x03fc)
#define REG_PIN_U2TXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x0400)
#define REG_PIN_U2RXD                   SCI_ADDRESS(CTL_PIN_BASE, 0x0404)
#define REG_PIN_NFCEN1                  SCI_ADDRESS(CTL_PIN_BASE, 0x0408)
#define REG_PIN_SCL0                    SCI_ADDRESS(CTL_PIN_BASE, 0x040c)
#define REG_PIN_SDA0                    SCI_ADDRESS(CTL_PIN_BASE, 0x0410)
#define REG_PIN_SCL2                    SCI_ADDRESS(CTL_PIN_BASE, 0x0414)
#define REG_PIN_SDA2                    SCI_ADDRESS(CTL_PIN_BASE, 0x0418)
#define REG_PIN_SCL3                    SCI_ADDRESS(CTL_PIN_BASE, 0x041c)
#define REG_PIN_SDA3                    SCI_ADDRESS(CTL_PIN_BASE, 0x0420)
#define REG_PIN_LCD_D18                 SCI_ADDRESS(CTL_PIN_BASE, 0x0424)
#define REG_PIN_LCD_D19                 SCI_ADDRESS(CTL_PIN_BASE, 0x0428)
#define REG_PIN_LCD_D20                 SCI_ADDRESS(CTL_PIN_BASE, 0x042c)
#define REG_PIN_LCD_D21                 SCI_ADDRESS(CTL_PIN_BASE, 0x0430)
#define REG_PIN_LCD_D22                 SCI_ADDRESS(CTL_PIN_BASE, 0x0434)
#define REG_PIN_LCD_D23                 SCI_ADDRESS(CTL_PIN_BASE, 0x0438)
#define REG_PIN_TRACECLK                SCI_ADDRESS(CTL_PIN_BASE, 0x043c)
#define REG_PIN_TRACECTRL               SCI_ADDRESS(CTL_PIN_BASE, 0x0440)
#define REG_PIN_TRACEDAT0               SCI_ADDRESS(CTL_PIN_BASE, 0x0444)
#define REG_PIN_TRACEDAT1               SCI_ADDRESS(CTL_PIN_BASE, 0x0448)
#define REG_PIN_TRACEDAT2               SCI_ADDRESS(CTL_PIN_BASE, 0x044c)
#define REG_PIN_TRACEDAT3               SCI_ADDRESS(CTL_PIN_BASE, 0x0450)
#define REG_PIN_TRACEDAT4               SCI_ADDRESS(CTL_PIN_BASE, 0x0454)
#define REG_PIN_TRACEDAT5               SCI_ADDRESS(CTL_PIN_BASE, 0x0458)
#define REG_PIN_TRACEDAT6               SCI_ADDRESS(CTL_PIN_BASE, 0x045c)
#define REG_PIN_TRACEDAT7               SCI_ADDRESS(CTL_PIN_BASE, 0x0460)
#define REG_PIN_SIMCLK2                 SCI_ADDRESS(CTL_PIN_BASE, 0x0464)
#define REG_PIN_SIMDA2                  SCI_ADDRESS(CTL_PIN_BASE, 0x0468)
#define REG_PIN_SIMRST2                 SCI_ADDRESS(CTL_PIN_BASE, 0x046c)
#define REG_PIN_SIMCLK3                 SCI_ADDRESS(CTL_PIN_BASE, 0x0470)
#define REG_PIN_SIMDA3                  SCI_ADDRESS(CTL_PIN_BASE, 0x0474)
#define REG_PIN_SIMRST3                 SCI_ADDRESS(CTL_PIN_BASE, 0x0478)
#define REG_PIN_XXX                     SCI_ADDRESS(CTL_PIN_BASE, 0x0000)

/* bits definitions for register REG_PIN_XXX */
#define BITS_PIN_DS(_x_)                ( (_x_) << 8 & (BIT(8)|BIT(9)) )
#define BIT_PIN_WPU                     ( BIT(7) )
#define BIT_PIN_WPD                     ( BIT(6) )
#define BITS_PIN_AF(_x_)                ( (_x_) << 4 & (BIT(4)|BIT(5)) )
#define BIT_PIN_SLP_WPU                 ( BIT(3) )
#define BIT_PIN_SLP_WPD                 ( BIT(2) )
#define BIT_PIN_SLP_IE                  ( BIT(1) )
#define BIT_PIN_SLP_OE                  ( BIT(0) )

/* vars definitions for controller CTL_PIN */
#define BIT_PIN_NUL                     ( 0 )
#define BIT_PIN_SLP_NUL                 ( 0 )
#define BIT_PIN_SLP_Z                   ( 00 )

#endif //__CTL_PIN_H__
