# core framebuffer
#
obj-y:= fb_main.o fb_rrm.o lcdc_manager.o

# lcd driver
#

#obj-y+= sc8800g_lcd_s6d0139.o
obj-$(CONFIG_MACH_SP8810) += lcd_hx8369.o
obj-$(CONFIG_MACH_SC8810OPENPHONE)+=lcd_hx8357.o


