
# core framebuffer
#
#obj-$(CONFIG_MACH_HISENSE) := sc8800s_fb.o
#obj-$(CONFIG_MACH_HISENSE) += sc8800s_lcd_ili9328.o

#obj-$(CONFIG_MACH_BIGPHONE) := sc8800s_lcm0_fb.o
#obj-$(CONFIG_MACH_BIGPHONE) += sc8800s_lcd_r61581.o
obj-y:= sc8800g_fb.o sc8800g_rrm.o sc8800g_lcdc_manager.o
obj-y+= sc8800g_copybit_lcdc.o
obj-y+= sc8800g_copybit_scale.o
obj-y+= sc8800g_copybit_rotation.o
obj-y+= sc8800g_2d.o
obj-$(CONFIG_MACH_G2PHONE)+=sc8800g_lcd_ili9328.o
obj-$(CONFIG_MACH_OPENPHONE)+=sc8800g_lcd_hx8357.o
obj-$(CONFIG_MACH_SP6810A)+=sc8800g_lcd_hx8357.o
