
# core framebuffer
#
#obj-$(CONFIG_MACH_HISENSE) := sc8800s_fb.o
#obj-$(CONFIG_MACH_HISENSE) += sc8800s_lcd_ili9328.o

#obj-$(CONFIG_MACH_BIGPHONE) := sc8800s_lcm0_fb.o
#obj-$(CONFIG_MACH_BIGPHONE) += sc8800s_lcd_r61581.o
obj-y:= sc8800g_fb.o
obj-y+= sc8800g_lcd_ili9328.o
