# SC88XX Platform Support

#obj-$(CONFIG_SND_SC88XX_SOC_SPRDPHONE) += sprdphone.o vbc-codec.o sc88xx-vbc.o sc88xx-pcm.o
#obj-y += sensor_2655.o sensor.o dcam_drv_sc8800s.o dcam.o
#obj-m += sensor_2655.o sensor.o dcam_drv_sc8800s.o dcam.o dcam_v4l2.o
#sprd_dcam-objs := sensor_2655.o sensor.o dcam_drv_sc8800s.o dcam.o dcam_v4l2.o
sprd_dcam_sc8800g2-objs := sensor_cfg.o sensor_drv.o sensor_gc0309.o sensor_gt2005_new.o sensor_ov2655.o sensor_ov7675.o sensor_ov7690.o dcam_sc8800g2.o dcam_drv_sc8800g2.o dcam_v4l2_sc8800g2.o
#obj-m += sprd_dcam_sc8800g2.o
obj-y += sprd_dcam_sc8800g2.o
