
obj-$(CONFIG_FB_SC8810) := sprdfb_main.o lcdpanel.o lcdc.o

obj-$(CONFIG_FB_LCD_HX8369) += lcd_hx8369.o

obj-$(CONFIG_FB_LCD_HX8357) += lcd_hx8357.o
obj-$(CONFIG_FB_LCD_ILI9486) += lcd_ili9486.o
obj-$(CONFIG_FB_LCD_HX8357_OPENPHONE) += lcd_hx8357_openphone.o
