
ifeq ($(CONFIG_MACH_COREPRIMELITE),y)
obj-y += sensor_power_coreprimelite.o
else ifeq ($(CONFIG_MACH_COREPRIMELITE_MARLIN),y)
obj-y += sensor_power_coreprimelite_marlin.o
else
obj-y += sensor_power.o
endif

