# SPRD Platform Support
snd-soc-sprd-vbc-objs       := vbc.o
obj-$(CONFIG_SND_SPRD_SOC_VBC)       += snd-soc-sprd-vbc.o
snd-soc-sprd-vbc-v2-objs       := vbc_r2p0.o
obj-$(CONFIG_SND_SPRD_SOC_VBC_R2P0)    += snd-soc-sprd-vbc-v2.o
snd-soc-sprd-vbc-pcm-objs       := sprd-vbc-pcm.o
obj-$(CONFIG_SND_SPRD_SOC_VBC)       += snd-soc-sprd-vbc-pcm.o
obj-$(CONFIG_SND_SPRD_SOC_VBC_R2P0)    += snd-soc-sprd-vbc-pcm.o